### ISSUE TITLE
Error from server (SeviceUnavailable): the server is currently unable to handle the request

### ISSUE THREAD

**Issue by djarotech** [cloud-ark/kubediscovery#1]
![errr](https://user-images.githubusercontent.com/11185590/41494312-051bbd68-70d7-11e8-8cd7-40e58b0238a5.png)

The first three steps ran fine, when I was verifying I ran into this ^

**Comment by devdattakulkarni** [comment]
Can you check kubectl get pods -n provenance? What output do you see?

Run kubectl logs pod-name -n provenance -c container-name

to see the logs of the Pod. What output do you see?

Usually it takes few minutes for the api server to start responding. If the logs show no errors, try above commands again couple of times.

**Comment by djarotech** [comment]
![screenshot from 2018-06-15 22-00-35](https://user-images.githubusercontent.com/11185590/41495199-9070a18e-70e7-11e8-8d46-49f83d7c22ab.png)

**Comment by djarotech** [comment]
Oh it might be because i ran the cleanup delete command already, i'll retry it

**Comment by djarotech** [comment]
The "delete-provenance-artifacts.sh"

**Comment by djarotech** [comment]
![err](https://user-images.githubusercontent.com/11185590/41495260-bda09ba4-70e8-11e8-94b0-51e6dceeddad.png)

I now reran it after I started over and ran steps 1 and 2 and got these problems

**Comment by djarotech** [comment]
![err](https://user-images.githubusercontent.com/11185590/41495463-7daac7cc-70ed-11e8-8d53-2f891d779af8.png)
did a kubectl describe ..

**Comment by devdattakulkarni** [comment]
Looks like the Image is not being pulled.

**Comment by devdattakulkarni** [comment]
What you need to do is following: eval $(minikube docker-env)

This will allow locally built images to be pulled by Minikube

**Comment by djarotech** [comment]
Yes this did work!
I made a separate issue,
I am now having some problems with the lister.
