### ISSUE TITLE
Get dynamic composition for all deployments, has no output. Reflector failed to list

### ISSUE THREAD

**Issue by djarotech** [cloud-ark/kubediscovery#2]
![err3](https://user-images.githubusercontent.com/11185590/41499767-c26b8be0-714b-11e8-943a-419dd044c1bc.png)

kubectl logs outputted this:
![err2](https://user-images.githubusercontent.com/11185590/41499743-66183f82-714b-11e8-9d96-f9c8d061bdf6.png)

Reflector failed to list, *v1beta1...k8s.io is forbidden. Cannot list validatingwebhookconfigurations.admissionregistration.k8s.io at the cluster scope

**Comment by devdattakulkarni** [comment]
You are trying to get compositions for etcdclusters resource which you don't have I suppose (since you have not installed the Etcd Operator).

Try following:
- Delete the deployment
- Modify the kind_compositions.yaml to get rid of Etcd definition
- Deploy again

Query for compositions for one of the kinds defined in your kind_compositions.yaml

**Comment by devdattakulkarni** [comment]
I have pushed a commit that removes EtcdCluster definition from kind_compositions.yaml.

Please pull master and try.

**Comment by djarotech** [comment]
okay

**Comment by djarotech** [comment]
Same issue in the logs
![screenshot from 2018-06-16 11-07-01](https://user-images.githubusercontent.com/11185590/41500375-aa7e498c-7155-11e8-9825-734968607764.png)

**Comment by devdattakulkarni** [comment]
Can you check the the logs of the kube-provenance-apiserver-6r7qw Pod?

Check Troubleshooting tips to get the exact logs command

**Comment by djarotech** [comment]
![err34](https://user-images.githubusercontent.com/11185590/41500402-2960df30-7156-11e8-80e4-3ab499bc2b38.png)

**Comment by devdattakulkarni** [comment]
Also, check if the Aggregated API server endpoint has registered or not.

kubectl get --raw /apis | python -mjson.tool 

In this output do you see the kubeprovenance.cloudark.io api endpoint?

**Comment by djarotech** [comment]
yes
![screenshot from 2018-06-16 11-13-11](https://user-images.githubusercontent.com/11185590/41500411-4650bf0c-7156-11e8-81de-76497fda7011.png)

**Comment by devdattakulkarni** [comment]
Okay, good to know that the endpoint has registered correctly.

But the API server is running into some permission issue. Let me dig into the permissions that we grant the API server (in one of the deployment artifact files). Will have an update soon.

**Comment by djarotech** [comment]
ok

**Comment by djarotech** [comment]
There's some similar issues if you do a google search of different parts of the error, here's one
https://github.com/kubernetes/client-go/issues/375

**Comment by devdattakulkarni** [comment]
I have just pushed a change. Can you pull and try again.

**Comment by djarotech** [comment]
okay

**Comment by djarotech** [comment]
![ss](https://user-images.githubusercontent.com/11185590/41500689-341b793e-715c-11e8-8623-11449a6680e7.png)
Looks like that did something! here's the logs, and queries. services gave some output

**Comment by devdattakulkarni** [comment]
This is promising.

**Comment by devdattakulkarni** [comment]
Can you deploy something and then check the provenance again for deployments.

**Comment by djarotech** [comment]
![screenshot from 2018-06-16 12-11-22](https://user-images.githubusercontent.com/11185590/41500821-6e2a7b6e-715e-11e8-84bd-741943db0a90.png)
Looks good! Should I close the issue

**Comment by devdattakulkarni** [comment]
Great!!

This is perfect. Yes, you can close the issue.
