### ISSUE TITLE
Remove excessive log output

### ISSUE THREAD

**Issue by devdattakulkarni** [cloud-ark/kubediscovery#27]
Here is how current output from discovery apiserver looks like. We should trim this.

$kubectl logs kubeplus-gzzs7 -c kube-discovery-apiserver

KIND_COMPOSITION_FILE not provided
Getting value for /operators
Error:100: Key not found (/operators) [3]
crdListString:
KIND_COMPOSITION_FILE not provided
Getting value for /operators
Error:100: Key not found (/operators) [3]
crdListString:
I1120 20:09:47.510831       1 serving.go:273] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
I1120 20:09:48.299765       1 plugins.go:158] Loaded 2 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,MutatingAdmissionWebhook.
I1120 20:09:48.299791       1 plugins.go:161] Loaded 1 validating admission controller(s) successfully in the following order: ValidatingAdmissionWebhook.
W1120 20:09:48.300758       1 genericapiserver.go:319] Skipping API kubeplus.cloudark.io/v1 because it has no resources.
Explain PATH:/apis/kubeplus.cloudark.io/v1/explain
I1120 20:09:48.301119       1 serve.go:96] Serving securely on [::]:443
KIND_COMPOSITION_FILE not provided
Getting value for /operators
Error:100: Key not found (/operators) [3]
crdListString:
KIND_COMPOSITION_FILE not provided
Getting value for /operators
Error:100: Key not found (/operators) [3]
crdListString:
KIND_COMPOSITION_FILE not provided
Getting value for /operators
Error:100: Key not found (/operators) [3]
crdListString:
KIND_COMPOSITION_FILE not provided
Getting value for /operators
Error:100: Key not found (/operators) [3]
crdListString:
KIND_COMPOSITION_FILE not provided
Getting value for /operators
Error:100: Key not found (/operators) [3]
crdListString:
KIND_COMPOSITION_FILE not provided
Getting value for /operators
Error:100: Key not found (/operators) [3]
crdListString:
KIND_COMPOSITION_FILE not provided
Getting value for /operators
Error:100: Key not found (/operators) [3]
crdListString:
KIND_COMPOSITION_FILE not provided
Getting value for /operators
Error:100: Key not found (/operators) [3]
crdListString:
KIND_COMPOSITION_FILE not provided
Getting value for /operators

**Comment by djarotech** [comment]
I have not been able to reproduce this error . Personally I believe this error will not occur anymore by the looks of it. Do you know how to reproduce it ? 
The `Getting value for /operators` is now commented, and it looks like the `Error Key not found /operators ` is closely related to the queryETCD error, when no key was found in etcd. Fixed here: https://github.com/cloud-ark/kubediscovery/pull/42


As for the KIND_COMPOSITION_FILE, I can suggest returning early in the err!=nil block below, so that we do not unmarshal nothing
```go

func readKindCompositionFile() {
	// read from the opt file
	filePath, ok := os.LookupEnv("KIND_COMPOSITION_FILE")
	if ok {
		yamlFile, err := ioutil.ReadFile(filePath)
		if err != nil {
			fmt.Printf("Error reading file:%s", err)
		}

		compositionsList := make([]composition, 0)
		err = yaml.Unmarshal(yamlFile, &compositionsList)

```

**Comment by devdattakulkarni** [comment]
I remember fixing the main log output. 

About your suggestion for returning early from readKindCompositionFile(), it makes sense.

Can you create a PR for that?

In the commit message you can add link to this issue "Fixes: <url for this issue>"

**Comment by devdattakulkarni** [comment]
@danielpygo ^

**Comment by djarotech** [comment]
Ok sure
