### ISSUE TITLE
Conflicting imports, go.etcd.io/etcd/client causing build failure

### ISSUE THREAD

**Issue by djarotech** [cloud-ark/kubediscovery#43]
The recently changed import "go.etcd.io/etcd/client" is causing a conflict with "github.com/ugorji/go".
Current master is unable to build correctly bc of this. Atom changed the import from

"github.com/coreos/etcd/client" to "go.etcd.io/etcd/client" and I committed this in the latest refactoring code fyi
 
$ ./build-local-discovery-artifacts.sh
 github.com/cloud-ark/kubediscovery/vendor/go.etcd.io/etcd/client
vendor/go.etcd.io/etcd/client/keys.generated.go:70:6: r.WriteArrayStart undefined (type codec.encDriver has no field or method WriteArrayStart)
vendor/go.etcd.io/etcd/client/keys.generated.go:72:6: r.WriteMapStart undefined (type codec.encDriver has no field or method WriteMapStart)
vendor/go.etcd.io/etcd/client/keys.generated.go:75:6: r.WriteArrayElem undefined (type codec.encDriver has no field or method WriteArrayElem)
vendor/go.etcd.io/etcd/client/keys.generated.go:83:6: r.WriteMapElemKey undefined (type codec.encDriver has no field or method WriteMapElemKey)
vendor/go.etcd.io/etcd/client/keys.generated.go:85:6: r.WriteMapElemValue undefined (type codec.encDriver has no field or method WriteMapElemValue)
vendor/go.etcd.io/etcd/client/keys.generated.go:94:6: r.WriteArrayElem undefined (type codec.encDriver has no field or method WriteArrayElem)
vendor/go.etcd.io/etcd/client/keys.generated.go:102:6: r.WriteMapElemKey undefined (type codec.encDriver has no field or method WriteMapElemKey)
vendor/go.etcd.io/etcd/client/keys.generated.go:104:6: r.WriteMapElemValue undefined (type codec.encDriver has no field or method WriteMapElemValue)
vendor/go.etcd.io/etcd/client/keys.generated.go:113:6: r.WriteArrayElem undefined (type codec.encDriver has no field or method WriteArrayElem)
vendor/go.etcd.io/etcd/client/keys.generated.go:121:6: r.WriteMapElemKey undefined (type codec.encDriver has no field or method WriteMapElemKey)
vendor/go.etcd.io/etcd/client/keys.generated.go:121:6: too many errors

**Comment by devdattakulkarni** [comment]
Fixed in https://github.com/cloud-ark/kubediscovery/commit/ecc4d6fd9e7b1747cdf3d3dccb40e0a367ff9892
